// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'landing__bg': string;
  'landing__nav': string;
  'landing__nav__items': string;
  'landing__nav__items__first': string;
  'landing__title': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
