// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'landing__bg': string;
  'landing__hands': string;
  'landing__navigation': string;
}
export const cssExports: CssExports;
export default cssExports;
